# Prefix key
set-option -g prefix C-a
bind-key C-a send-prefix
unbind C-b

# Split panes
bind | split-window -h
bind - split-window -v

# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded!"

# Mouse support
set -g mouse on

# Start windows at 1
set -g base-index 1
setw -g pane-base-index 1

# History
set -g history-limit 10000
